---
title: "House Pricing"
author: "Shashank Semwal"
date: "10 August 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(psych)
library(car)
library(dplyr)
```

```{r}
house_data<-read.csv("C:/Users/Shashank/Documents/R/dataset/home credit default/kc_house_data.csv")
```

```{r}
#ID column not necessary
house_data<-house_data[,-1]
# Structure
str(house_data)
```

Calculating Variance Inflation Factor
inorder to calculate multicollanity among the independent variable
```{r}

house_data<-house_data %>% select(-sqft_living)
vif(lm(price~., house_data))
alias(lm(price~., house_data))
# we conclude that sqft_living is the variable giving us low variance hence we will remove it

```

```{r}
# convert date to date datatype
house_data$date<-as.Date(strtrim(house_data$date,8),format="%Y%m%d")
# Age from Date
house_data$date<-as.numeric((Sys.Date()-house_data$date)/365)
```


```{r}
# Sampling
sample<-sample(nrow(house_data),size = 0.7*nrow(house_data))
house_train<-house_data[sample,]
house_test<-house_data[-sample,]
```

```{r}
pairs.panels(house_data[1:5])
```


```{r}
# MODEL
house_model<-lm(price~.,data = house_train)
house_predict<-predict(house_model,house_test[,-2])

```

```{r}
summary(house_model)
```

```{r}
# Check for Heteroskedasticity
plot(house_model$residuals)

#we can see there is no Hetroskedasticity

```

```{r}
house_rmse<-sqrt(sum((house_model$residuals^2))/nrow(house_train))
house_rmse
```

```{r}
plot(house_model)
```

```{r}
# R Square
house_rsquare<- 1 - sum((house_model$residuals^2))/sum((house_train$price-mean(house_train$price))^2)
  
```

```{r}
#Adjusted R Square
house_adjustRSquare<-(1-house_rsquare)*17/(nrow(house_train)-17)
```


REGULARIZATION
```{r}
library(leaps)

house_reg<-regsubsets(x = price~.,data = house_train,nvmax = 19,method = "backward")

plot(house_reg,scale = 'adjr2')

```

```{r}
# SO WE CONCLUDE THAT OUT REGULARIZATION ON TRAINING SET INCREASES THE MODEL ACCURACY
```


